class Payment < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # security ..................................................................
  # relationships .............................................................
  belongs_to :order, touch: true
  belongs_to :source, polymorphic: true
  belongs_to :payment_method
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  delegate :name, to: :payment_method, prefix: true
  delegate :number, to: :order, prefix: true
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
