class Shipment < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  include ShipmentStateTracking
  # security ..................................................................
  # relationships .............................................................
  belongs_to :order, touch: true
  belongs_to :address

  has_many :shipping_rates, dependent: :delete_all
  has_many :shipping_methods, through: :shipping_rates
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  accepts_nested_attributes_for :address
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
