class ShippingMethod < ActiveRecord::Base
  # extends ...................................................................
  acts_as_paranoid
  # includes ..................................................................
  # security ..................................................................
  # relationships .............................................................
  has_many :shipping_rates
  has_many :shipments, through: :shipping_rates
  has_many :shipping_method_categories
  has_many :shipping_categories, through: :shipping_method_categories
  # validations ...............................................................
  validates :name, presence: true
  validate :at_least_one_shipping_category
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  DISPLAY = [:both, :front_end, :back_end]
  METHODS = self.all.map { |s| [s.name, s.id] }
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
  private
    def at_least_one_shipping_category
      if self.shipping_categories.empty?
        self.errors[:shipping_category_ids] << "You need to select at least one shipping category"
      end
    end
end
