class ShippingRate < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # security ..................................................................
  # relationships .............................................................
  belongs_to :shipment
  belongs_to :shipping_method
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  scope :with_shipping_method,
      -> { includes(:shipping_method).
           references(:shipping_method).
           order("cost ASC") }
  # additional config .........................................................
  delegate :order, to: :shipment
  delegate :name, to: :shipping_method
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
